//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.gimi.dlnagimi;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.VideoView;
import com.gimi.dlnagimi.R.id;
import com.gimi.dlnagimi.R.layout;

public final class TestActivity_
    extends TestActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_test);
    }

    private void init_(Bundle savedInstanceState) {
        initDatas();
    }

    private void afterSetContentView_() {
        videoView1 = ((VideoView) findViewById(id.videoView1));
        imageView1 = ((ImageView) findViewById(id.imageView1));
        button1 = ((Button) findViewById(id.button1));
        {
            View view = findViewById(id.button1);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        TestActivity_.this.button1();
                    }

                }
                );
            }
        }
        initWidgets();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static TestActivity_.IntentBuilder_ intent(Context context) {
        return new TestActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, TestActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public TestActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
